#!/bin/sh
# This would fail for grep-2.5.3
: ${srcdir=.}
. "$srcdir/init.sh"; path_prepend_ ../src

printf 'A\nZ\n'      > exp1 || framework_failure
fail=0

for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
  printf 'A\n1\nZ\n.\n' | LC_ALL=$LOC grep -i '[a-z]' > out1 || fail=1
  compare out1 exp1 || fail=1
done

# This actually passes also for grep-2.5.3
printf 'a\nz\n'      > exp2 || framework_failure

for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
  printf 'a\n1\nz\n.\n' | LC_ALL=$LOC grep -i '[A-Z]' > out2 || fail=1
  compare out2 exp2 || fail=1
done

Exit $fail
