#!/bin/sh
# This test would segfault for grep-2.14
. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_en_utf8_locale_
require_compiled_in_MB_support

printf 'é\n'      > exp1 || framework_failure_
fail=0

for LOC in en_US.UTF-8 $LOCALE_FR_UTF8; do
  out=out4-$LOC
  printf 'á\nç\né\n' | LC_ALL=$LOC grep -E '([^.]*[é]){1,2}' > $out || fail=1
  compare exp1 $out || fail=1
done

Exit $fail
