#!/bin/sh
# Outputting to /dev/null.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_timeout_

${AWK-awk} 'BEGIN {while (1) print "x"}' </dev/null |
  timeout 10 grep x >/dev/null || fail=1

Exit $fail
