#!/bin/sh
# Outputting to /dev/null.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_timeout_

${AWK-awk} 'BEGIN {while (1) print "x"}' </dev/null |
  timeout 1 grep x >/dev/null
test $? -eq 124 || fail=1

Exit $fail
