#!/bin/sh
# Ensure that --mmap is ignored
. "${srcdir=.}/init.sh"; path_prepend_ ../src

echo a > in || framework_failure_
fail=0

grep --mmap a in > out 2>&1 || fail=1
compare out in || fail=1

grep --mmap b in > out 2>&1
# Expect no match and no output.
test $? = 1 || fail=1
compare out /dev/null || fail=1

Exit $fail
