#!/bin/sh
# Ensure that we don't trigger a grep -F infloop.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_en_utf8_locale_
require_compiled_in_MB_support
require_timeout_

encode() { echo "$1" | tr A '\202'; }

encode AA > input

fail=0

# Before 2.15, this would infloop.
LC_ALL=en_US.UTF-8 timeout 3 grep -F $(encode A) input > out || fail=1
compare input out || fail=1

Exit $fail
