#!/bin/sh
# grep-2.17 would take nearly 200x longer to run the command below.

# Copyright 2014 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
require_timeout_

fail=0

require_JP_EUC_locale_

yes $(printf '%078d' 0) | head -50000 > in || framework_failure_

# Expect no match, i.e., exit status of 1.  Anything else is an error.
timeout 4 grep -i foobar in; st=$?
test $st = 1 || fail=1

Exit $fail
