#! /bin/sh
# Show how to make grep -P abort.
#
# Copyright (C) 2011 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
require_pcre_

fail=0

echo aaaaaaaaaaaaaab > in || framework_failure_
grep -P '((a+)*)+$' in > out || fail=1
compare in out || fail=1

Exit $fail
