#!/bin/sh
# This would mistakenly print a line prior to grep-2.18.
. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_en_utf8_locale_
require_compiled_in_MB_support

encode() { echo "$1" | tr ABC '\357\274\241'; }

encode ABC >exp1
encode aABC >exp2

fail=0

for LOC in en_US.UTF-8 $LOCALE_FR_UTF8; do
  for type in dfa fgrep regex; do
    case $type in
      dfa) opt= prefix= ;;
      fgrep) opt=-F prefix= ;;
      regex) opt= prefix='\(\)\1' ;;
    esac
    out=out-$type-$LOC
    LC_ALL=$LOC grep $opt "$prefix$(encode A)" exp1 >$out || fail=1
    compare exp1 $out || fail=1
    LC_ALL=$LOC grep $opt "$prefix$(encode aA)" exp2 >$out || fail=1
    compare exp2 $out || fail=1
  done
done

Exit $fail
