#!/bin/sh
# Check that "grep -r PAT" reads ".".
. "${srcdir=.}/init.sh"; path_prepend_ ../src

mkdir dir || framework_failure_
echo aaa > dir/a || framework_failure_
echo bbb > dir/b || framework_failure_

echo a:aaa > exp || framework_failure_

for p in "" "-p"; do
  (cd dir && grep $p -r aaa) > out || fail=1
  compare exp out || fail=1

  (cd dir && grep $p -r aaa < a) > out || fail=1
  compare exp out || fail=1

  (cd dir && grep $p -r aaa *) > out || fail=1
  compare exp out || fail=1
done

Exit $fail
