#!/bin/sh
# exercise \< and \> with multibyte data.
# Derived from http://savannah.gnu.org/bugs/?29537
. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_en_utf8_locale_

echo 'é' > in || framework_failure_
LC_ALL=en_US.UTF-8
export LC_ALL

fail=0
grep '\<é' in > out 2>err || fail=1

compare out in || fail=1
compare err /dev/null || fail=1

Exit $fail
