#!/bin/sh
# This would fail for grep-2.20
. "${srcdir=.}/init.sh"; path_prepend_ ../src

require_en_utf8_locale_

printf '\xc3\xa1\n' > in || framework_failure_
LC_ALL=en_US.UTF-8
export LC_ALL

fail=0

for LOC in en_US.UTF-8 zh_CN.UTF-8 $LOCALE_FR_UTF8; do
  out=out1-$LOC
  LC_ALL=$LOC grep '\w' in >$out || fail=1
  compare in $out || fail=1

  out=out2-$LOC
  LC_ALL=$LOC grep '\W' in >$out && fail=1
  compare /dev/null $out || fail=1
done

Exit $fail
